### ISSUE TITLE
2 openvpn processes - provided solution for finding the 'parent' does not work.

### ISSUE THREAD

**Issue by ghost** [expressvpn/expressvpn_leak_testing#6]
xv_leak_tools/test_components/vpn_application/desktop_vpn_application.py
 line 142+ has the below comment

This is a bit of a hack. Some providers are known to spawn two openvpn instances. We only want the parent one which is the one where --config is specified. So if we find more than one the we will let this slide if exactly one of them has --config in it.

I have 2 openvpn processes and neither has config. I cant see a way of easily getting the parent pid (for both NX systems and windows systems) without using a package such as psutil. 

Im happy to have a go at implamenting something more robust, if you have some pointers of they way you would like to see it done?

**Comment by expressvpn** [comment]
Unfortunately, psutil doesn't work with Cygwin. Another approach might be to instead look for long argument strings. It's not amazingly robust either, but might be good enough for now considering it's an edge case. Suggestions and PRs are very welcome.

**Comment by ghost** [comment]
Good initial idea, I will add another block if the existing " contains --config" does not return a single process.
