### ISSUE TITLE
expressvpn doesn't block traffic on unexpectedly connection drops

### ISSUE THREAD

**Issue by ghost** [expressvpn/expressvpn_leak_testing#7]
My system:
Ubuntu 18.04

expressvpn version: 2.0.0 (56d99d4)

After running expressvpn I get the following message:
```
expressvpn connect countryname
Connected to Country - ...

   - To check your connection status, type 'expressvpn status'.
   - If your VPN connection unexpectedly drops, internet traffic will be blocked to protect your privacy.
   - To disable Network Lock, disconnect ExpressVPN then type 'expressvpn preferences set network_lock off'.
```
I have now experienced a connection drop, so status shows me also unable to connect:
```
expressvpn status
Unable to connect.

   - Check your internet connection or try a different location.
   - Internet traffic is blocked to protect your privacy.
   - To retry the connection, type 'expressvpn connect'
   - To disconnect from the VPN and unblock internet traffic, type 'expressvpn disconnect'
```
The problem is, that expressvpn is telling me `Internet traffic is blocked to protect your privacy` but I am online and writing this issue here right now. Also I have checked my ip `https://www.expressvpn.com/what-is-my-ip` and it shows me the city I am living in. So who is protecting me right now?

**Comment by expressvpn-jacque** [comment]
Hi @saitam1, sorry to hear you are having trouble with Network Lock. Can you please contact support by going to https://www.expressvpn.com/support/ and clicking on the Live Chat button, they will be happy to help out and escalate to the engineering team if necessary. Thank you.
