### ISSUE TITLE
Bug introduced in "run_tests.py / log.py" due to breaking change in TTYColoredFormatter

### ISSUE THREAD

**Issue by MiguelAngel-Moreno** [expressvpn/expressvpn_leak_testing#8]
Hello.

I installed your "**expressvpn_leak_testing**" in my macOS computer.  When trying to run the tests I got an "unrecoverable error" at line 79 of "`/xv_leak_tools/log.py`" (see attached file 
[bug__initializing_colored_log_20190326.txt](https://github.com/expressvpn/expressvpn_leak_testing/files/3007660/bug__initializing_colored_log_20190326.txt)).

After analysing your code, I found the cause of the bug to be a recent breaking change in the newest version of `class TTYColoredFormatter` (v4.0.0).  The change was posted by the `colorlog.py` Python package main author last December (see [here for the change in the code](https://github.com/borntyping/python-colorlog/commit/40280b4bb36d8ad1a8bf1cfaa159a4a9066b1126)).

I have uploaded the fix for this bug in the attached [log_py_20190326_patch.txt](https://github.com/expressvpn/expressvpn_leak_testing/files/3007670/log_py_20190326_patch.txt) patch file (change the extension from `.txt` to `.patch` before applying the patch, or edit the code manually).

I read the discussion of "**Issue #4 correct exception handler**" about creating a branch for committing fixes by external users there instead of in the main branch, but so far no additional branch was created ( `develop`, `features`, etc. ).

I would like to help not only with code fixes, but also with the "**Get started**" documentation ...  I personally ran into a couple of issues that took considerable time to get solved (more than 1 hour) and that are not covered by the documentation (I am using a macOS computer, the "recommended option" for starters, and I still had trouble to "_get started quickly_"... 😁 )

**Comment by expressvpn-jacque** [comment]
@MiguelAngel-Moreno thanks for this report and appreciate the patch. You are welcome to fork this repository and submit a pull request for any bug fixes or improvements to the documentation. Looking forward to your contributions.
